#!/bin/bash

outputdestination=../../paper-JITD-Journal/testlogs/rawtestlog.txt
echo -e "\nRunning testsuite on $(date "+%m-%d-%Y %H:%M:%S")\n" >> $outputdestination
for f in src/test/testsuite/*.txt
do
  echo $f >> $outputdestination
  ./btree $f >> $outputdestination
done
